name: Contexto
run-name: ¡Estoy aprendiendo a usar Contextos!
on: push
jobs:
  check-aprendiendo-github-actions:
    if: ${{ github.ref == 'refs/heads/aprendiendo-github-actions' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Desplegando en la rama $GITHUB_REF"
  check-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Desplegando en la rama $GITHUB_REF"
